In [1]:
import torch
import numpy as np
import pickle
import os
import pandas as pd

In [2]:
bidaf_embedding= pd.read_pickle('./data/train/no_random_word_embeddings.pkl')
bidaf_embedding[9]

array([-0.27086  ,  0.044006 , -0.02026  , -0.17395  ,  0.6444   ,
        0.71213  ,  0.3551   ,  0.47138  , -0.29637  ,  0.54427  ,
       -0.72294  , -0.0047612,  0.040611 ,  0.043236 ,  0.29729  ,
        0.10725  ,  0.40156  , -0.53662  ,  0.033382 ,  0.067396 ,
        0.64556  , -0.085523 ,  0.14103  ,  0.094539 ,  0.74947  ,
       -0.194    , -0.68739  , -0.41741  , -0.22807  ,  0.12     ,
       -0.48999  ,  0.80945  ,  0.045138 , -0.11898  ,  0.20161  ,
        0.39276  , -0.20121  ,  0.31354  ,  0.75304  ,  0.25907  ,
       -0.11566  , -0.029319 ,  0.93499  , -0.36067  ,  0.5242   ,
        0.23706  ,  0.52715  ,  0.22869  , -0.51958  , -0.79349  ,
       -0.20368  , -0.50187  ,  0.18748  ,  0.94282  , -0.44834  ,
       -3.6792   ,  0.044183 , -0.26751  ,  2.1997   ,  0.241    ,
       -0.033425 ,  0.69553  , -0.64472  , -0.0072277,  0.89575  ,
        0.20015  ,  0.46493  ,  0.61933  , -0.1066   ,  0.08691  ,
       -0.4623   ,  0.18262  , -0.15849  ,  0.020791 ,  0.1937

In [3]:
bidaf_word2idx = pd.read_pickle('./data/train/word2idx.pkl')
bidaf_word2idx['a']

9

In [4]:
bert_embeddings = pd.read_pickle('./context/content_embed.pkl')
print(type(bert_embeddings))

<class 'collections.OrderedDict'>


In [5]:
bert_embeddings["a"]

array([-4.69497490e+00, -5.33880055e-01, -5.72718441e-01, -4.65749025e-01,
        6.82471514e-01, -6.07614040e-01,  3.28209543e+00,  1.68689013e+00,
        2.48324347e+00, -1.10488221e-01, -9.24110234e-01, -1.81867397e+00,
       -4.02614450e+00,  1.27208734e+00, -2.85645485e+00,  3.92821342e-01,
        1.82029915e+00, -1.89068627e+00, -1.17136225e-01,  1.75828934e+00,
        3.28554249e+00, -2.13329768e+00,  9.83984828e-01,  4.98288298e+00,
        1.10319102e+00, -3.84457111e-01,  2.20141554e+00, -4.10292387e-01,
        3.63706946e-01,  2.72713327e+00, -8.76196861e-01,  5.39998710e-03,
       -8.06998909e-01, -2.82843518e+00, -6.34000421e-01, -2.43827701e+00,
        1.36898160e+00, -5.36697090e-01,  2.01924324e-01, -1.20317504e-01,
       -3.11609924e-01, -3.18405747e-01,  7.40516782e-02,  2.32178020e+00,
       -1.98769188e+00, -4.34296668e-01,  1.30530643e+00, -3.22069669e+00,
       -1.30523694e+00, -4.69250536e+00, -1.35202813e+00, -3.24198627e+00,
       -9.99793828e-01, -

In [6]:
outOfVocab = 0
not_found = 0
matched = 0
bidaf_ed = 0

for key in bidaf_word2idx:
    index = bidaf_word2idx[key]

    if np.all(bidaf_embedding[index] == 1):
        try:
            bidaf_embedding[index] = np.concatenate([bert_embeddings[key],bert_embeddings[key]])
            outOfVocab += 1
        except:
            bidaf_embedding[index] = np.random.normal(0, 0.1, 200)
            not_found += 1
    else:
        try:
            bidaf_embedding[index] = np.concatenate([bidaf_embedding[index],bert_embeddings[key]])
            matched += 1

        except:
            bidaf_embedding[index] = np.concatenate([bidaf_embedding[index],bidaf_embedding[index]])
            bidaf_ed =+ 1

In [9]:
print(outOfVocab)
print(not_found)
print(matched)
print(bidaf_ed)

52
59426
16517
1


In [4]:
beta = qaa

In [5]:
type(beta)

list

In [9]:
beta

-0.33171

In [10]:
charlie = pd.read_pickle('./data/train/word2idx.pkl')
charlie['a']

9

In [ ]:
for 

In [33]:
for key in charlie:
    index = charlie[key]

    try:
        bidaf_embedding[index] = np.concatenate([bidaf_embedding[index],bert_embeddings[key]])
        print("Done")

    except:
        bidaf_embedding[index] = np.concatenate([bidaf_embedding[index],bidaf_embedding[index]])
        print("error avoided")

avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanating
error avoided
concatanatin

In [35]:
beta[5]

array([-0.33978999,  0.20941   ,  0.46348   , -0.64792001, -0.38376999,
        0.038034  ,  0.17127   ,  0.15978   ,  0.46619001, -0.019169  ,
        0.41479   , -0.34349   ,  0.26872   ,  0.04464   ,  0.42131001,
       -0.41032001,  0.15459   ,  0.022239  , -0.64652997,  0.25255999,
        0.043136  , -0.19445001,  0.46516001,  0.45651001,  0.68588001,
        0.091295  ,  0.21875   , -0.70350999,  0.16785   , -0.35078999,
       -0.12634   ,  0.66384   , -0.25819999,  0.036542  , -0.13605   ,
        0.40253001,  0.14289001,  0.38132   , -0.12283   , -0.45886001,
       -0.25281999, -0.30432001, -0.11215   , -0.26181999, -0.22482   ,
       -0.44554001,  0.29910001, -0.85611999, -0.14503001, -0.49085999,
        0.0082973 , -0.17490999,  0.27524   ,  1.44009995, -0.21239001,
       -2.8434999 , -0.27958   , -0.45721999,  1.63859999,  0.78807998,
       -0.55261999,  0.64999998,  0.086426  ,  0.39012   ,  1.0632    ,
       -0.35378999,  0.48328   ,  0.34599999,  0.84174001,  0.09

In [37]:
charlie[]

{'--NULL--': 0,
 '--UNK--': 1,
 'the': 2,
 ',': 3,
 'of': 4,
 '.': 5,
 'and': 6,
 'in': 7,
 'to': 8,
 'a': 9,
 '"': 10,
 '-': 11,
 'is': 12,
 'was': 13,
 'The': 14,
 'as': 15,
 ')': 16,
 '(': 17,
 '?': 18,
 'for': 19,
 'by': 20,
 'that': 21,
 'with': 22,
 "'s": 23,
 'on': 24,
 'from': 25,
 'are': 26,
 'were': 27,
 'In': 28,
 'which': 29,
 'or': 30,
 'at': 31,
 'an': 32,
 'What': 33,
 'be': 34,
 'it': 35,
 ' ': 36,
 'his': 37,
 'have': 38,
 'has': 39,
 'not': 40,
 'their': 41,
 'also': 42,
 'its': 43,
 'had': 44,
 ';': 45,
 'first': 46,
 'but': 47,
 'one': 48,
 'other': 49,
 'did': 50,
 'such': 51,
 'this': 52,
 'been': 53,
 'most': 54,
 'many': 55,
 'more': 56,
 'what': 57,
 'who': 58,
 'into': 59,
 'he': 60,
 'city': 61,
 'they': 62,
 'used': 63,
 'can': 64,
 'all': 65,
 'two': 66,
 ':': 67,
 '%': 68,
 'than': 69,
 'time': 70,
 "'": 71,
 'between': 72,
 'century': 73,
 'after': 74,
 'some': 75,
 'during': 76,
 'over': 77,
 'only': 78,
 'United': 79,
 'It': 80,
 'new': 81,
 'when': 82,

In [13]:
type(charlie)

dict

In [19]:
trial = beta[90]

In [20]:
trial

array([ 0.29019 ,  0.80497 ,  0.31187 , -0.32706 , -0.47237 ,  1.1363  ,
       -0.37966 ,  0.11569 ,  0.41912 ,  0.016284, -0.06543 , -0.004047,
        0.77688 , -0.24936 ,  0.18817 , -0.64008 , -0.02027 , -0.18528 ,
       -1.0651  ,  0.69115 ,  1.0472  ,  0.36171 ,  0.80863 , -0.42767 ,
       -0.18299 , -0.27847 ,  0.43839 , -0.023336,  0.37359 , -0.3588  ,
        0.47261 ,  0.73946 ,  0.015123,  0.059862, -0.066841, -0.38842 ,
        0.22361 ,  0.8057  ,  0.33789 , -0.052222, -1.1057  , -0.1113  ,
        0.15101 , -0.66649 , -0.044992, -0.068159,  0.098957, -0.55942 ,
       -0.78109 , -0.50947 , -0.37327 , -0.75674 ,  0.22583 ,  1.2963  ,
       -0.48181 , -1.818   ,  0.38529 , -0.21849 ,  2.2418  ,  0.20094 ,
       -0.35208 ,  1.4893  , -0.21701 , -0.24615 ,  0.55185 ,  0.97224 ,
        0.58526 , -0.029754,  0.57944 , -0.64798 , -0.12371 , -0.53459 ,
       -0.20528 , -0.53599 ,  0.30895 ,  0.53935 ,  0.11853 ,  0.42749 ,
       -1.0872  , -0.23409 ,  0.73882 ,  0.15749 , 

In [24]:
trial.append(alpha['a'])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [25]:
import numpy as np

In [31]:
np.concatenate([trial,alpha['a']])

array([ 2.90190011e-01,  8.04970026e-01,  3.11870009e-01, -3.27060014e-01,
       -4.72369999e-01,  1.13629997e+00, -3.79660010e-01,  1.15690000e-01,
        4.19120014e-01,  1.62840001e-02, -6.54300004e-02, -4.04699985e-03,
        7.76880026e-01, -2.49359995e-01,  1.88170001e-01, -6.40079975e-01,
       -2.02699993e-02, -1.85279995e-01, -1.06509995e+00,  6.91150010e-01,
        1.04719996e+00,  3.61710012e-01,  8.08629990e-01, -4.27670002e-01,
       -1.82990000e-01, -2.78470010e-01,  4.38389987e-01, -2.33360007e-02,
        3.73589993e-01, -3.58799994e-01,  4.72609997e-01,  7.39459991e-01,
        1.51230004e-02,  5.98619990e-02, -6.68409988e-02, -3.88419986e-01,
        2.23609999e-01,  8.05700004e-01,  3.37889999e-01, -5.22219986e-02,
       -1.10570002e+00, -1.11299999e-01,  1.51010007e-01, -6.66490018e-01,
       -4.49919999e-02, -6.81589991e-02,  9.89570022e-02, -5.59419990e-01,
       -7.81090021e-01, -5.09469986e-01, -3.73270005e-01, -7.56739974e-01,
        2.25830004e-01,  

In [28]:
type(trial)

numpy.ndarray

In [29]:
trial

array([ 0.29019 ,  0.80497 ,  0.31187 , -0.32706 , -0.47237 ,  1.1363  ,
       -0.37966 ,  0.11569 ,  0.41912 ,  0.016284, -0.06543 , -0.004047,
        0.77688 , -0.24936 ,  0.18817 , -0.64008 , -0.02027 , -0.18528 ,
       -1.0651  ,  0.69115 ,  1.0472  ,  0.36171 ,  0.80863 , -0.42767 ,
       -0.18299 , -0.27847 ,  0.43839 , -0.023336,  0.37359 , -0.3588  ,
        0.47261 ,  0.73946 ,  0.015123,  0.059862, -0.066841, -0.38842 ,
        0.22361 ,  0.8057  ,  0.33789 , -0.052222, -1.1057  , -0.1113  ,
        0.15101 , -0.66649 , -0.044992, -0.068159,  0.098957, -0.55942 ,
       -0.78109 , -0.50947 , -0.37327 , -0.75674 ,  0.22583 ,  1.2963  ,
       -0.48181 , -1.818   ,  0.38529 , -0.21849 ,  2.2418  ,  0.20094 ,
       -0.35208 ,  1.4893  , -0.21701 , -0.24615 ,  0.55185 ,  0.97224 ,
        0.58526 , -0.029754,  0.57944 , -0.64798 , -0.12371 , -0.53459 ,
       -0.20528 , -0.53599 ,  0.30895 ,  0.53935 ,  0.11853 ,  0.42749 ,
       -1.0872  , -0.23409 ,  0.73882 ,  0.15749 , 

In [30]:
np.hstack(trial,alpha['a'])

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given